---
DashID: bis
Rows:
-
    Row: 0
    chartType: TITLE
    Title: "BIS SDMX Dashboard Generator"
    Subtitle: "This is a demo of the BIS SDMX Dashboard Generator"
-
    Row: 0
    chartType: FOOTER
    Title:  "2023 SDMX Global Conference Hackathon - Bank for International Settlements"
    Subtitle:  "The views expressed are those of the authors and do not necessarily reflect those of the Bank for International Settlements. All errors are our own."
-
    Row: 1
    chartType: VALUE
    Title:  "Unemployment rate"
    Subtitle:  Example of a dashboard script with data from Chile
    Unit: "%" 
    unitLoc: SUFFIX
    Decimals: "{$DECIMALS}"
    LabelsYN: No
    legendConcept: 
    legendLoc: 
    xAxisConcept: TIME_PERIOD
    yAxisConcept: OBS_VALUE
    downloadYN: 
    dataLink: 
    metadataLink: 
    DATA: "https://stats.bis.org/api/v1/data/WS_CBPOL_M/M.AR/all?detail=full&format=csv"
-
    Row: 1
    chartType: VALUE
    Title: "Number of persons with multiple jobs"
    Subtitle: "Number of persons with multiple jobs"
    Unit: 
    unitLoc: HIDE
    Decimals: 0
    LabelsYN: No
    legendConcept: 
    legendLoc: 
    xAxisConcept: TIME_PERIOD
    yAxisConcept: OBS_VALUE
    downloadYN: 
    dataLink: 
    metadataLink: 
    DATA: "https://stats.bis.org/api/v1/data/WS_CBPOL_M/M.AR/all?detail=full&format=csv"
-
    Row: 1
    chartType: VALUE
    Title:  "NEET - Youth not in employment, education or training"
    Subtitle:  "Number of persons with multiple jobs"
    Unit: "%"
    unitLoc: SUFFIX
    Decimals: 2
    LabelsYN: No
    legendConcept: 
    legendLoc: 
    xAxisConcept: TIME_PERIOD
    yAxisConcept: OBS_VALUE
    downloadYN: 
    dataLink: 
    metadataLink: 
    DATA: "https://stats.bis.org/api/v1/data/WS_CBPOL_M/M.AR/all?detail=full&format=csv"
-
    Row: 2
    chartType: LINE
    Title:  "Persons outside the labour force by sex"
    Subtitle: "Number of persons with multiple jobs"
    Unit: "%"
    unitLoc: SUFFIX
    Decimals: 0
    LabelsYN:  Yes
    legendConcept: SEX
    legendLoc: RIGHT
    xAxisConcept: TIME_PERIOD
    yAxisConcept: OBS_VALUE
    downloadYN: 
    dataLink: 
    metadataLink: 
    DATA: "https://stats.bis.org/api/v1/data/WS_CBPOL_M/M.AR/all?detail=full&format=csv"
-
    Row: 2
    chartType: VALUE
    Title: "{$MEASURE}"
    Subtitle: "{$TIME_PERIOD}"
    Unit: 
    unitLoc: HIDE
    Decimals: "{$DECIMALS}"
    LabelsYN: No
    legendConcept: 
    legendLoc: 
    xAxisConcept: TIME_PERIOD
    yAxisConcept: OBS_VALUE
    downloadYN: 
    dataLink: 
    metadataLink: 
    DATA: "https://stats.bis.org/api/v1/data/WS_CBPOL_M/M.AR/all?detail=full&format=csv"
-
    Row: 2
    chartType: LINE
    Title:  "Employment by economic activity"
    Subtitle:  "{$TIME_PERIOD}"
    Unit: "%"
    unitLoc: SUFFIX
    Decimals: 0
    LabelsYN:  Yes
    legendConcept: ECO
    legendLoc: HIDE
    xAxisConcept: TIME_PERIOD
    yAxisConcept: OBS_VALUE
    downloadYN: 
    dataLink: 
    metadataLink: 
    DATA: "https://stats.bis.org/api/v1/data/WS_CBPOL_M/M.AR/all?detail=full&format=csv"
-
    Row: 3
    chartType: LINES, double
    Title: "Labour Force participation rates"
    Subtitle: 
    Unit: 
    unitLoc: 
    Decimals: 0
    LabelsYN: No
    legendConcept: SEX
    legendLoc: BOTTOM
    xAxisConcept: TIME_PERIOD
    yAxisConcept: OBS_VALUE
    downloadYN: 
    dataLink: 
    metadataLink: 
    DATA: "https://stats.bis.org/api/v1/data/WS_CBPOL_M/M.AR/all?detail=full&format=csv"
-
    Row: 3
    chartType: BARS
    Title:  "Status in employment"
    Subtitle:  "{$TIME_PERIOD}"
    Unit: 
    unitLoc: HIDE
    Decimals: 0
    LabelsYN: Yes
    legendConcept: 
    legendLoc: HIDE
    xAxisConcept: TIME_PERIOD
    yAxisConcept: OBS_VALUE
    downloadYN: 
    dataLink: 
    metadataLink: 
    DATA: "https://stats.bis.org/api/v1/data/WS_CBPOL_M/M.AR/all?detail=full&format=csv"
